Exam/Models/Hobby.cs
using System;
using System.ComponentModel.DataAnnotations;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;
namespace Exam.Models
{
    public class Hobby
    {
        [Key]
        public int HobbyId {get; set;}

        [Required]
        public string Name {get; set;}

        [Required]
        public string Description {get; set;}

        public int UserId {get;set;}
        public User Creator {get;set;}
        public List<UserHobby> UserHobby {get;set;} 

        public DateTime CreatedAt = DateTime.Now;
        public DateTime UpdatedAt = DateTime.Now;
    }
}

Exam/Controllers/HobbyController.cs
using System;
using System.Linq;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Exam.Models;
using Microsoft.EntityFrameworkCore;
using System.Collections.Generic;

namespace WeddingPlanner.Controllers
{
    public class HobbyController : Controller
    {
        private ExamContext DbContext;

        public HobbyController(ExamContext context)
        {
            DbContext = context;
        } 

        [HttpGet("Dashboard")]
        public IActionResult Dashboard()
        {
            if (HttpContext.Session.GetInt32("uid") != null)
            {
                int id = (int)HttpContext.Session.GetInt32("uid");
                List<Hobby> ListHobby = DbContext.Hobbies
                .Include(h=>h.Creator)
                .Include(h=>h.UserHobby)
                .ThenInclude(u=>u.User)
                .ToList();
                ViewBag.UserID = id;
            
            return View("Dashboard", ListHobby);
            }
            else
            {
                return RedirectToAction("Index", "User");
            }
        }

        [HttpGet("AddHobby")]
        public ViewResult AddHobby()
        {
            return View();
        }

        [HttpPost("new")]
          public IActionResult Create(Hobby newHobby)
        {
           if(ModelState.IsValid)
            {
                  if(DbContext.Hobbies.Any(h=>h.Name == newHobby.Name))
                {
                    ModelState.AddModelError("Name", "This hobby is already exist!");
                    return View("AddHobby");
                }
                
                    newHobby.UserId = (int) HttpContext.Session.GetInt32("uid");
                    DbContext.Hobbies.Add(newHobby);
                    DbContext.SaveChanges();
                    return Redirect("/Dashboard");
                
            }
            else
            {
                return View("AddHobby");
            }
        }

        [HttpGet("Details/{HobbyID}")]
        public IActionResult Details(int HobbyID)
        {
            int id = (int)HttpContext.Session.GetInt32("uid");
            ViewBag.UserID = id;
            Hobby ThisHobby = DbContext.Hobbies
            .Include(w=>w.UserHobby)
            .ThenInclude(u=>u.User)
            .FirstOrDefault(w=>w.HobbyId == HobbyID);
            return View("Details", ThisHobby);
        }



        [HttpGet("enthusiast/{HobbyID}")]
        public IActionResult Enthusiast(int HobbyID)
        {
            UserHobby ThisEnthusiast = new UserHobby();
            ThisEnthusiast.UserId = (int)HttpContext.Session.GetInt32("uid");
            ThisEnthusiast.HobbyId = HobbyID;
            DbContext.UserHobbies.Add(ThisEnthusiast);
            DbContext.SaveChanges();
            return RedirectToAction("Dashboard");

        }
        
        

        [HttpGet("edit/{HobbyID}")]
        public IActionResult Edit(int HobbyID)
        {
            Hobby thisHobby = DbContext.Hobbies.FirstOrDefault(h=>h.HobbyId == HobbyID);
            return View(thisHobby);
        }

        [HttpPost("editH/{HobbyID}")]
        public IActionResult EditProcess(int HobbyID, Hobby EditH)
        {
            Hobby thisHobby = DbContext.Hobbies.FirstOrDefault(h=>h.HobbyId == HobbyID);

            if(ModelState.IsValid)
            {
                 if(DbContext.Hobbies.Any(h=>h.Name == EditH.Name))
                {
                    ModelState.AddModelError("Name", "This hobby is already exist!");
                    return View("Edit");
                }
                
                    thisHobby.Name = EditH.Name;
                    thisHobby.Description = EditH.Description;
                    thisHobby.UpdatedAt = DateTime.Now;
                    DbContext.SaveChanges();
                    return Redirect($"/Details/{thisHobby.HobbyId}");
                
            }
            else
            {
                return View("Edit");
            }

        }
        [HttpGet("logout")]
        public RedirectToActionResult Lougout(){
            HttpContext.Session.Clear();
            return RedirectToAction("Index", "User");
        }
    }
}

Exam/Views/Hobby/AddHobby.cshtml
@model Hobby
<p><a href="/Dashboard">Dashboard</a> | <a href="/logout">Logout</a></p>

    <div style=" display: flex; justify-content: space-evenly;" >
    <div >
        <h1>Create a Hobby</h1>
        <form asp-action="Create" asp-controller="Hobby" method="post">
            <div class="form-group">
                <p><span style="color: red;" asp-validation-for="Name"></span></p>
                <label asp-for="Name">Name</label>
                <input asp-for="Name" type="text" class="form-control"/>
            </div>
            <div class="form-group">
                <p><span style="color: red;" asp-validation-for="Description"></span></p>
                <label asp-for="Description">Description</label>
                <textarea name="Description" asp-for = "Description" cols="10" rows="5" class="form-control"></textarea>
            </div>
            
            <button class="btn btn-primary">Create</button>
        </form>
    </div>
    </div>

Exam/Views/Hobby/Dashboard.cshtml
@model List<Hobby>

<div class="Header" style="display: flex;">

    <h1 style="margin-right: 900px;">Hobbies</h1>
    <a href="/logout">Logout</a>

</div>

<table class="table">
    <tr>
        <th scope="col">Name</th>
        <th scope="col">Enthusiasts</th>
    
    </tr>
    @foreach (Hobby h in Model)
    {
        <tr>
            <td>
                <a href="Details/@h.HobbyId">@h.Name</a>
            </td>
            <td>
                @h.UserHobby.Count
            </td>
          
        </tr>
    }
    
</table>

<div class="footer">
    <a href="/AddHobby">Create a Hobby</a>
</div>

Exam/Views/Hobby/Details.cshtml
@model Hobby
<p><a href="/Dashboard">Dashboard</a> | <a href="/logout">Logout</a></p>
<h1 style="margin-bottom: 50px;">@Model.Name</h1>
<p>Description: @Model.Description</p>

<p>@Model.Name Enthusiasts: </p>
    @{ 
        foreach (var e in Model.UserHobby)
        {
        <ul style="margin-bottom: 50px; margin-top:20px">
            <li>@e.User.FName @e.User.LName</li> 
        </ul>
        }
    
    }

@{

if (!Model.UserHobby.Any( a => a.UserId == ViewBag.UserID))
    {
        <a href="/enthusiast/@Model.HobbyId"><button class="btn btn-dark">Add to Hoppies</button></a>
    }
                       
}


@{
    if(Model.UserId == ViewBag.UserID)
    {
        <a href="/edit/@Model.HobbyId"><button class="btn btn-dark">Edit</button></a>

    }
}
                

Exam/Views/Hobby/Edit.cshtml
@model Hobby
<p><a href="/Dashboard">Dashboard</a> | <a href="/logout">Logout</a></p>

    <div style=" display: flex; justify-content: space-evenly;" >
    <div >
        <h1>Edit a Hobby</h1>
        <form asp-action="EditProcess" asp-controller="Hobby" method="post">
            <div class="form-group">
                <p><span style="color: red;" asp-validation-for="Name"></span></p>
                <label asp-for="Name">Name</label>
                <input asp-for="Name" type="text" class="form-control"/>
            </div>
            <div class="form-group">
                <p><span style="color: red;" asp-validation-for="Description"></span></p>
                <label asp-for="Description">Description</label>
                <textarea name="Description" asp-for = "Description" cols="30" rows="5" class="form-control"></textarea>
            </div>
            
            <button class="btn btn-primary">Update</button>
        </form>
    </div>
    </div>